tyru/caw.vim

- autoload/caw.vim
- doc/caw.txt
[Slim](http://slim-lang.com) に対応しました。 :wink:
> Add slim support.

- autoload/caw.vim
nginxの設定ファイルのコメントに対応する設定を追加しました。
[Configuration File’s Structure - Beginner’s Guide](http://nginx.org/en/docs/beginners_guide.html#conf_structure)
> Support filetype 'nginx'

- autoload/caw/actions/wrap.vim
https://twitter.com/croce1/status/709600324172918784
> [Vim(let):E714: リスト型が必要です]::[function caw#keymapping_stub[42]..193[2]..218, 行 13]
> <Plug>(caw:wrap:comment) gives an error

- autoload/caw.vim
https://github.com/Shougo/context_filetype.vim
> Fix context_filetype.vim support isn't working

- appveyor.yml
https://github.com/thinca/vim-themis/issues/31
> See vim nightly build not +kaoriya version

- autoload/caw/actions/hatpos.vim
> Fix E117 "Unknown function s:make_indent_str"

- autoload/caw.vim
- plugin/caw.vim
Close #49 
Close #20
~~(This must be going to conflict with #48)~~
Resolved
> Add operators for each keymapping

- doc/caw.txt
> [Doc] Fix wrong mapping name <Plug>(caw:tildepos:toggle)

- autoload/caw.vim
> Support repeat.vim (make all mappings dot-repeatable)

- .travis.yml
- appveyor.yml
- test/.themisrc
* (Import vital.vim's config files)
* [appveyor.yml](https://github.com/vim-jp/vital.vim/blob/5248d1ad6eb19e9755215c1775ae16b5f85739e6/appveyor.yml)
* [.travis.yml](https://github.com/vim-jp/vital.vim/blob/ca4c3bf86fab43fe9f58b4949cd995b688bfe204/.travis.yml)
* Travis: Check multiple environments using `matrix`
* AppVeyor: Drop support for Vim 7.3
> Update CI config files (AppVeyor, Travis)

- after/ftplugin/arduino/caw.vim
just copy `cpp/caw.vim` to `arduino/caw.vim`
> Support arduino filetype

- after/ftplugin/egison/caw.vim
- macros/separate.vim
I add ftplugin file for egison (https://github.com/egison/egison).
Please merge it.
> add ftplugin file for egison

- after/ftplugin/vim/caw.vim
- autoload/caw.vim
- autoload/caw/actions/hatpos.vim
- macros/after-ftplugin-template.vim
- macros/generate-ftplugins.vim
> Support line continuation comment in ft=vim

- autoload/caw/actions/zeropos.vim
> [bg]:caw_zeropos_sp may have funcref

- .travis.yml
- macros/install-vim.sh
> Fix CI macos setting(ref: vital.vim setting)

- autoload/caw.vim
- autoload/caw/actions/wrap.vim
- doc/caw.txt
- test/actions/box.vim
- test/actions/dollarpos.vim
- test/actions/hatpos.vim
- test/actions/jump.vim
- test/actions/wrap.vim
- test/actions/zeropos.vim
> Support [count] for non-operator mappings

- autoload/caw/actions/hatpos.vim
> Remove indent when uncommented line is empty

- autoload/caw.vim
- autoload/caw/comments/base.vim
> Don't change &filetype directly

- autoload/caw.vim
- autoload/caw/actions/wrap.vim
- test/actions/box.vim
- test/actions/dollarpos.vim
- test/actions/hatpos.vim
- test/actions/jump.vim
- test/actions/wrap.vim
- test/actions/zeropos.vim
> Uncomment wrapped portion

- autoload/caw/actions/hatpos.vim
- autoload/caw/actions/zeropos.vim
- doc/caw.txt
- plugin/caw.vim
- test/actions/dollarpos.vim
> Deprecate g:caw_{hat,zero}pos_sp_blank

- .appveyor.yml
- .travis.yml
- autoload/caw/actions/hatpos.vim
- test/actions/hatpos.vim
- test/actions/zeropos.vim
fixes #129 
hatpos, zeropos では、行頭がコメントの場合のみ uncomment する。
> Fix hatpos:uncomment at the line with trailing comment

- after/ftplugin/qmake/caw.vim
- macros/generate-ftplugins.vim
Reference: https://doc.qt.io/archives/qt-4.8/qmake-project-files.html#comments
> Support qmake .pro files

- macros/after-ftplugin-template.vim
- macros/generate-ftplugins.vim
> [CI] Fix generate ftplugins was failed

- autoload/caw.vim
- autoload/caw/comments.vim
- autoload/caw/comments/oneline.vim
- autoload/caw/comments/wrap_oneline.vim
- doc/caw.txt
- plugin/caw.vim
via #165 
Merge some commits in above PR
- 123adca013e55f4a8c4f9e48461cd7563736e912
- 703db47ca390d939f58c4c16836f84369098986a
Incomplete but it works partly (@yuki-yano)
> (Workaround ver.) Integrate ts context commentstring

- autoload/caw/actions/traits/comment_detectable.vim
This makes caw.vim working with [vim-treesitter](https://github.com/mattn/vim-treesitter).
> Check vim8 text properties

- after/ftplugin/yaml/caw.vim
- macros/generate-ftplugins.vim
Fix https://github.com/Shougo/context_filetype.vim/issues/56
> Add yaml support
